name: blog-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest
    name: 部署Hexo博客
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
          cache: "npm"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Install Dependencies
        run: npm install
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
